### ISSUE TITLE
판정핵 무한로딩 222

### ISSUE THREAD

**Issue by dringkbar** [MaxKss/shinycolors-perfect#2]
난 아무리 새로고침해도 계속 무한로딩되고 프로그램자체도 아예 확장프로그램 목록 들어가서 꺼야 페스할수있음 페스하다가 중간에 켜도 적용안됨 그래도 무한로딩 전까지 줠라 잘썼음 굳굳

**Comment by MaxKss** [comment]
앤자측에서 샤니마스를 업데이트하면 해당 코드도 새 버전에 맞게 바꿔줘야됨. 무한로딩은 업데이트에 내가 바로 맞추지 못해서 그런거고 새 버전 받으면 정상적으로 될거임
